### ISSUE TITLE
solutions/1_FEP_TheSensingWheel_Perception_sol.ipynb not working

### ISSUE THREAD

**Issue by elichou** [pl-robotdecision/tutorials-active-inference#1]
I get this error when loading `solutions/1_FEP_TheSensingWheel_Perception_sol.ipynb`:
`/1_FEP_TheSensingWheel_Perception_sol.ipynb NotJSONError('Notebook does not appear to be JSON: \'\\ufeff{\\n "cells": [\\n {\\n "cell_typ...')`

**Comment by pl-robotdecision** [comment]
Fixed. It was something related to the character coding.
